# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34d96bc89ceb4122e96f2029f311e8d323ba4deac9fb961c0af9d991857e0fce3769447e10f06580d4b06843fb46a7681fbd263d7e2c4550c0efba56442db795

test:
  secret_key_base: ad85cfe6ede70f0aef01db6c390e452848e12480cb052dd3512cd7b526fc35edbc8e31f226fb767a4d84baaa157ce24d5849cfac2f8fa333ffca506a9e9ecc9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
